<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	  <parent>
	    <artifactId>parent</artifactId>
	    <groupId>org.nasdanika.sdk.runtime.tests</groupId>
	    <version>2026.10.0</version>
	    <relativePath>..</relativePath>
	  </parent>
	<artifactId>telemetry</artifactId>
	<packaging>jar</packaging>
	<name>Telemetry</name>
	<description>Telemetry tests with SDK</description>
	<dependencies>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>common</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime.models</groupId>
			<artifactId>core</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk</artifactId>
			<scope>compile</scope>
		</dependency>		
	</dependencies>
</project>
