<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.nasdanika.sdk.runtime.models.telemetry</groupId>
		<version>2026.10.0</version>
		<artifactId>parent</artifactId>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>exporters</artifactId>
	<packaging>jar</packaging>
	<name>Nasdanika SDK Runtime Telemetry Model Exporter</name>

	<dependencies>
		<dependency>
			<groupId>${project.groupId}</groupId>
			<artifactId>model</artifactId>
			<version>${project.version}</version>
		</dependency>
		<dependency>
			<groupId>io.opentelemetry</groupId>
			<artifactId>opentelemetry-sdk</artifactId>
			<scope>compile</scope>
		</dependency>
		<dependency>
			<groupId>org.eclipse.emf</groupId>
			<artifactId>org.eclipse.emf.ecore.xmi</artifactId>
			<scope>test</scope>
		</dependency>
	</dependencies>
</project>
