<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	  <parent>
	    <artifactId>parent</artifactId>
	    <groupId>org.nasdanika.sdk.runtime</groupId>
	    <version>2026.10.0</version>
	    <relativePath>..</relativePath>
	  </parent>
	<groupId>org.nasdanika.sdk.runtime.tests</groupId>
	<artifactId>parent</artifactId>
	<packaging>pom</packaging>
	<name>Tests</name>
	<description>Tests which require service registration and code in main</description>
	<properties>
	    <maven.deploy.skip>true</maven.deploy.skip>
	</properties>
	<modules>
		<module>general</module>
		<module>telemetry</module>
	</modules>	
</project>
