<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>
	<parent>
		<groupId>org.nasdanika.sdk.runtime</groupId>
		<artifactId>parent</artifactId>
		<version>2026.10.0</version>
		<relativePath>..</relativePath>
	</parent>
	<artifactId>all</artifactId>
	<packaging>pom</packaging>
	<name>Nasdanika SDK Runtime All</name>
	<description>All modules for Nasdanika SDK Runtime</description>

	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.nasdanika.sdk.runtime</groupId>
				<artifactId>bom</artifactId>
				<version>${project.version}</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>	

	<dependencies>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>common</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>emf-json</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>picocli</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>volume</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>groovy</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime</groupId>
			<artifactId>cli</artifactId>
		</dependency>
		<dependency>
			<groupId>org.nasdanika.sdk.runtime.models</groupId>
			<artifactId>all</artifactId>
			<type>pom</type>
		</dependency>

	</dependencies>
	
</project>
